apiVersion: batch/v1
kind: Job
metadata:
  name: tech-order-api-migration
  namespace: orders-service
spec:
  template:
    spec:
      containers:
      - name: migration
        image: ${DOCKER_IMAGE}
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tech-order-api-secret
              key: DATABASE_URL
        - name: NODE_ENV
          value: "production"
      restartPolicy: Never
  backoffLimit: 3 