apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: orders-service
type: Opaque
data:
  # These values will be populated from GitHub secrets during deployment
  RABBITMQ_USER: "${RABBITMQ_USER_B64}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD_B64}" 