apiVersion: v1
kind: Secret
metadata:
  name: tech-order-api-secret
  namespace: orders-service
type: Opaque
data:
  # These values should be base64 encoded
  # Example: echo -n "your-database-url" | base64
  DATABASE_URL: "" # Will be set manually or via CI/CD
  RABBITMQ_URI: "" # Will be set manually or via CI/CD
  # Add other sensitive environment variables here 